enum StoreActions {
    GET_PROJECTS = 'GET_PROJECTS',
    SAVE_PROJECT = 'SAVE_PROJECT',
    UPDATE_PROJECT = 'UPDATE_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    GET_TASKS = 'GET_TASKS',
    SAVE_TASK = 'SAVE_TASK',
    UPDATE_TASK = 'UPDATE_TASK',
    DELETE_TASK = 'DELETE_TASK',
}

export default StoreActions;