enum StoreMutations {
    LOAD_PROJECTS = 'LOAD_PROJECTS',
    SAVE_PROJECT = 'SAVE_PROJECT',
    UPDATE_PROJECT = 'UPDATE_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    LOAD_TASKS = 'LOAD_TASKS',
    SAVE_TASK = 'SAVE_TASK',
    UPDATE_TASK = 'UPDATE_TASK',
    DELETE_TASK = 'DELETE_TASK',
    NOTIFY = 'NOTIFY',
}

export default StoreMutations;